version: '3.8'
name: airport-compose-spring
services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_DB=airport-management-db
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  spring-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-api
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_USERNAME=user1
      - DB_PASSWORD=12345
      - DB_URL=jdbc:postgresql://postgres-db:5432/airport-management-db
      - DB_DRIVER=org.postgresql.Driver
      - appName.allowedApi=*
    depends_on:
      - postgres-db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "5050:80"
    depends_on:
      - postgres-db

volumes:
  postgres-data:
    driver: local
